/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AuthEImzo: typeof import('./src/components/auth/EImzo.vue')['default']
    CriteriaModal: typeof import('./src/components/CriteriaModal.vue')['default']
    LeftOutlined: typeof import('@ant-design/icons-vue')['LeftOutlined']
    MailFilled: typeof import('@ant-design/icons-vue')['MailFilled']
    Map: typeof import('./src/components/map/index.vue')['default']
    MapCounter: typeof import('./src/components/map/counter.vue')['default']
    MapRating: typeof import('./src/components/map/rating.vue')['default']
    MapRepublic: typeof import('./src/components/map/republic.vue')['default']
    MenuOutlined: typeof import('@ant-design/icons-vue')['MenuOutlined']
    PhoneFilled: typeof import('@ant-design/icons-vue')['PhoneFilled']
    RightOutlined: typeof import('@ant-design/icons-vue')['RightOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StageModal: typeof import('./src/components/StageModal.vue')['default']
    TheActions: typeof import('./src/components/TheActions.vue')['default']
    TheBreadcrumb: typeof import('./src/components/TheBreadcrumb.vue')['default']
    TheFilter: typeof import('./src/components/TheFilter.vue')['default']
    TheTable: typeof import('./src/components/TheTable.vue')['default']
    TheUserInfo: typeof import('./src/components/TheUserInfo.vue')['default']
    UpOutlined: typeof import('@ant-design/icons-vue')['UpOutlined']
    UserModal: typeof import('./src/components/UserModal.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    WorkerHierarchy: typeof import('./src/components/WorkerHierarchy.vue')['default']
  }
}
